Repository AY2324S1-CS2103T-T15-2/tp, pull requests merged in 2023-10, with the labels that each got.

#26 Add in photo, role details and PPP
  docs/AboutUs.md
  docs/images/chongweijie29.png
  docs/team/chongweijie29.md
Labels: type.Documentation, priority.High

#28 Add in some features for UG
  docs/UserGuide.md
  docs/images/ui/Ui-add.png
Labels: type.Documentation, priority.High

#34 Edit add feature, command summary in user guide
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#36 Add delete to User Guide
  docs/UserGuide.md
  docs/images/ui/Ui-delete.png
Labels: type.Documentation, priority.High

#37 First draft of Developer Guide
  docs/DevOps.md
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High

#38 Add list cmd and standardise image size for cmds in UG
  docs/UserGuide.md
  docs/images/ui/Ui-list.png
Labels: type.Documentation, priority.High

#40 Add list today in UG
  docs/UserGuide.md
  docs/images/ui/Ui-list_today.png
Labels: type.Documentation, priority.High

#41 Add take command in UG
  docs/UserGuide.md
  docs/images/ui/UI-take.png
Labels: type.Documentation, priority.High

#42 Add Use Case for List Today command
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High

#43 Standardise all v1.1 progress so far.
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/ui/Ui-take.png
Labels: type.Documentation, priority.High

#49 Make changes to set baseline for v1.2
  .github/workflows/gradle.yml
  docs/AboutUs.md
  docs/UserGuide.md
  src/main/java/seedu/address/Main.java
  src/main/java/seedu/address/MainAppPrescription.java
  src/main/java/seedu/address/logic/LogicManagerPrescription.java
  src/main/java/seedu/address/logic/LogicPrescription.java
  src/main/java/seedu/address/logic/MessagesPrescription.java
  src/main/java/seedu/address/logic/commands/AddPrescriptionCommand.java
  src/main/java/seedu/address/logic/commands/CommandPrescription.java
  src/main/java/seedu/address/logic/parser/AddPrescriptionCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntaxPrescription.java
  src/main/java/seedu/address/logic/parser/ParserPrescription.java
  src/main/java/seedu/address/logic/parser/ParserUtilPrescription.java
  src/main/java/seedu/address/logic/parser/PrescriptionListParser.java
  src/main/java/seedu/address/model/ModelManagerPrescription.java
  src/main/java/seedu/address/model/ModelPrescription.java
  src/main/java/seedu/address/model/PrescriptionList.java
  src/main/java/seedu/address/model/ReadOnlyPrescriptionList.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefsPrescription.java
  src/main/java/seedu/address/model/UserPrefsPrescription.java
  src/main/java/seedu/address/model/prescription/Date.java
  src/main/java/seedu/address/model/prescription/Dosage.java
  src/main/java/seedu/address/model/prescription/Frequency.java
  src/main/java/seedu/address/model/prescription/Name.java
  src/main/java/seedu/address/model/prescription/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/prescription/Note.java
  src/main/java/seedu/address/model/prescription/Prescription.java
  src/main/java/seedu/address/model/prescription/Stock.java
  src/main/java/seedu/address/model/prescription/UniquePrescriptionList.java
  src/main/java/seedu/address/model/prescription/exceptions/DuplicatePrescriptionException.java
  src/main/java/seedu/address/model/prescription/exceptions/PrescriptionNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtilPrescription.java
  src/main/java/seedu/address/storage/JsonAdaptedPrescription.java
  src/main/java/seedu/address/storage/JsonPrescriptionListStorage.java
  src/main/java/seedu/address/storage/JsonSerializablePrescriptionList.java
  src/main/java/seedu/address/storage/JsonUserPrefsStoragePrescription.java
  src/main/java/seedu/address/storage/PrescriptionListStorage.java
  src/main/java/seedu/address/storage/StorageManagerPrescription.java
  src/main/java/seedu/address/storage/StoragePrescription.java
  src/main/java/seedu/address/storage/UserPrefsStoragePrescription.java
  src/main/java/seedu/address/ui/MainWindowPrescription.java
  src/main/java/seedu/address/ui/PrescriptionCard.java
  src/main/java/seedu/address/ui/PrescriptionListPanel.java
  src/main/java/seedu/address/ui/UiManagerPrescription.java
  src/main/resources/view/MainWindowPrescription.fxml
  src/main/resources/view/PrescriptionListCard.fxml
  src/main/resources/view/PrescriptionListPanel.fxml
Labels: type.Task, priority.High

#55 V1.2 list
  src/main/java/seedu/address/logic/commands/ListPrescriptionCommand.java
  src/main/java/seedu/address/logic/parser/ListPrescriptionCommandParser.java
  src/main/java/seedu/address/logic/parser/PrescriptionListParser.java
  src/main/java/seedu/address/ui/PrescriptionCard.java
Labels: type.Story, priority.High

#54 V1.2 listToday
  src/main/java/seedu/address/logic/commands/ListTodayPrescriptionCommand.java
  src/main/java/seedu/address/logic/parser/ListTodayPrescriptionCommandParser.java
  src/main/java/seedu/address/logic/parser/PrescriptionListParser.java
  src/main/java/seedu/address/model/prescription/Date.java
  src/main/java/seedu/address/model/prescription/Frequency.java
  src/main/java/seedu/address/model/prescription/IsTodayPredicate.java
Labels: type.Story, priority.High

#56 Add ConsumptionCount
  src/main/java/seedu/address/model/prescription/ConsumptionCount.java
  src/main/java/seedu/address/model/prescription/Prescription.java
  src/main/java/seedu/address/ui/PrescriptionCard.java
  src/main/resources/view/PrescriptionListCard.fxml
Labels: type.Story, priority.High

#60 Set up baseline for the test codes and fix bugs
  src/main/java/seedu/address/logic/MessagesPrescription.java
  src/main/java/seedu/address/logic/commands/ListPrescriptionCommand.java
  src/main/java/seedu/address/model/prescription/Frequency.java
  src/main/java/seedu/address/storage/JsonAdaptedPrescription.java
  src/test/data/JsonPrescriptionListStorageTest/invalidAndValidPrescriptionList.json
  src/test/data/JsonPrescriptionListStorageTest/invalidPrescriptionList.json
  src/test/data/JsonPrescriptionListStorageTest/notJsonFormatPrescriptionList.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/JsonSerializablePrescriptionListTest/duplicatePrescriptionList.json
  src/test/data/JsonSerializablePrescriptionListTest/invalidPrescriptionList.json
  src/test/data/JsonSerializablePrescriptionListTest/typicalPrescriptionList.json
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerPrescriptionTest.java
  src/test/java/seedu/address/logic/commands/CommandPrescriptionTestUtil.java
  src/test/java/seedu/address/logic/commands/ListPrescriptionCommandTest.java
  src/test/java/seedu/address/logic/parser/CommandPrescriptionParserTestUtil.java
  src/test/java/seedu/address/logic/parser/ListPrescriptionCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilPrescriptionTest.java
  src/test/java/seedu/address/logic/parser/PrescriptionListParserTest.java
  src/test/java/seedu/address/model/ModelManagerPrescriptionTest.java
  src/test/java/seedu/address/model/PrescriptionListTest.java
  src/test/java/seedu/address/model/UserPrefsPrescriptionTest.java
  src/test/java/seedu/address/model/prescription/DateTest.java
  src/test/java/seedu/address/model/prescription/DosageTest.java
  src/test/java/seedu/address/model/prescription/FrequencyTest.java
  src/test/java/seedu/address/model/prescription/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/prescription/NameTest.java
  src/test/java/seedu/address/model/prescription/NoteTest.java
  src/test/java/seedu/address/model/prescription/PrescriptionTest.java
  src/test/java/seedu/address/model/prescription/StockTest.java
  src/test/java/seedu/address/model/prescription/UniquePrescriptionListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPrescriptionTest.java
  src/test/java/seedu/address/storage/JsonPrescriptionListStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializablePrescriptionListTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStoragePrescriptionTest.java
  src/test/java/seedu/address/storage/StorageManagerPrescriptionTest.java
  src/test/java/seedu/address/testutil/PrescriptionBuilder.java
  src/test/java/seedu/address/testutil/PrescriptionListBuilder.java
  src/test/java/seedu/address/testutil/PrescriptionUtil.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalPrescriptions.java
Labels: type.Task, priority.High

#62 Add delete command
  src/main/java/seedu/address/logic/MessagesPrescription.java
  src/main/java/seedu/address/logic/commands/DeletePrescriptionCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntaxPrescription.java
  src/main/java/seedu/address/logic/parser/DeletePrescriptionCommandParser.java
  src/main/java/seedu/address/logic/parser/PrescriptionListParser.java
Labels: type.Task, priority.High

#61 Add take command
  src/main/java/seedu/address/logic/commands/TakePrescriptionCommand.java
  src/main/java/seedu/address/logic/parser/AddPrescriptionCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntaxPrescription.java
  src/main/java/seedu/address/logic/parser/PrescriptionListParser.java
  src/main/java/seedu/address/logic/parser/TakePrescriptionCommandParser.java
  src/main/java/seedu/address/model/ModelManagerPrescription.java
  src/main/java/seedu/address/model/ModelPrescription.java
  src/main/java/seedu/address/model/prescription/Prescription.java
  src/main/java/seedu/address/model/prescription/SameNamePredicate.java
  src/main/java/seedu/address/model/prescription/Stock.java
  src/main/java/seedu/address/model/util/SampleDataUtilPrescription.java
  src/main/java/seedu/address/storage/JsonAdaptedPrescription.java
  src/main/java/seedu/address/ui/PrescriptionCard.java
  src/test/data/JsonSerializablePrescriptionListTest/duplicatePrescriptionList.json
  src/test/data/JsonSerializablePrescriptionListTest/typicalPrescriptionList.json
  src/test/java/seedu/address/storage/JsonAdaptedPrescriptionTest.java
  src/test/java/seedu/address/testutil/PrescriptionBuilder.java
  src/test/java/seedu/address/testutil/PrescriptionUtil.java
  src/test/java/seedu/address/testutil/TypicalPrescriptions.java
Labels: type.Story, priority.High

#63 Branch testdelete
  src/main/java/seedu/address/logic/commands/DeletePrescriptionCommand.java
  src/test/java/seedu/address/logic/commands/DeletePrescriptionCommandTest.java
  src/test/java/seedu/address/logic/parser/DeletePrescriptionCommandParserTest.java
Labels: type.Task, priority.Medium

#64 Add test for ListToday command.
  src/main/java/seedu/address/logic/commands/ListTodayPrescriptionCommand.java
  src/test/java/seedu/address/logic/commands/ListTodayPrescriptionCommandTest.java
  src/test/java/seedu/address/logic/parser/ListTodayPrescriptionCommandParserTest.java
Labels: type.Task, priority.High

#65 Remove Delete Person code
  docs/Testing.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/DeletePrescriptionCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeletePrescriptionCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Task, priority.Medium

#66 Add tests for TakePrescriptionCommand and TakePrescriptionCommandParser
  src/main/java/seedu/address/logic/commands/TakePrescriptionCommand.java
  src/main/java/seedu/address/model/prescription/ConsumptionCount.java
  src/main/java/seedu/address/model/prescription/Date.java
  src/main/java/seedu/address/model/prescription/Dosage.java
  src/main/java/seedu/address/model/prescription/Frequency.java
  src/main/java/seedu/address/model/prescription/Name.java
  src/main/java/seedu/address/model/prescription/Note.java
  src/main/java/seedu/address/model/prescription/Stock.java
  src/test/java/seedu/address/logic/commands/ListTodayPrescriptionCommandTest.java
  src/test/java/seedu/address/logic/commands/TakePrescriptionCommandTest.java
  src/test/java/seedu/address/logic/parser/TakePrescriptionCommandParserTest.java
  src/test/java/seedu/address/model/prescription/ConsumptionCountTest.java
Labels: type.Task, priority.Medium

#76 Standardise List cmd to ListToday
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: type.Enhancement, priority.Medium

#80 Add Edit Command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PrescriptionListParser.java
  src/test/data/JsonSerializablePrescriptionListTest/typicalPrescriptionList.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPrescriptionDescriptorTest.java
  src/test/java/seedu/address/testutil/EditPrescriptionDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalPrescriptions.java
Labels: type.Story, priority.High

#81 Add help command
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/PrescriptionListParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/parser/HelpCommandParserTest.java
Labels: type.Task, priority.Medium

#82 Add exit command
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/parser/ExitCommandParser.java
  src/main/java/seedu/address/logic/parser/PrescriptionListParser.java
  src/test/java/seedu/address/logic/parser/ExitCommandParserTest.java
Labels: type.Task, priority.Medium

#86 Improve take function and push isCompleted to prescription
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/TakeCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TakeCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/prescription/ConsumptionCount.java
  src/main/java/seedu/address/model/prescription/Prescription.java
  src/main/java/seedu/address/model/prescription/Stock.java
  src/main/java/seedu/address/storage/JsonAdaptedPrescription.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ListTodayCommandTest.java
  src/test/java/seedu/address/logic/commands/TakeCommandTest.java
  src/test/java/seedu/address/logic/parser/TakeCommandParserTest.java
  src/test/java/seedu/address/model/prescription/ConsumptionCountTest.java
  src/test/java/seedu/address/testutil/EditPrescriptionDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PrescriptionBuilder.java
Labels: type.Task, priority.Medium

#87 Edit delete command
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: type.Task, priority.High

#88 Include optional fields into BayMeds
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/TakeCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/prescription/IsTodayPredicate.java
  src/main/java/seedu/address/model/prescription/IsValidDatesPredicate.java
  src/main/java/seedu/address/model/prescription/Prescription.java
  src/main/java/seedu/address/storage/JsonAdaptedPrescription.java
  src/main/java/seedu/address/ui/PrescriptionCard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/TakeCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/prescription/PrescriptionTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPrescriptionTest.java
  src/test/java/seedu/address/testutil/EditPrescriptionDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PrescriptionBuilder.java
  src/test/java/seedu/address/testutil/PrescriptionUtil.java
Labels: type.Task, priority.High

#91 V1.3 GUI
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PrescriptionCard.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindowPrescription.fxml
  src/main/resources/view/PrescriptionListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/dummy.fxml
Labels: type.Task, priority.Medium

#83 Add find command
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/PrescriptionListParser.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: type.Task, priority.Medium

#95 add tests
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentMultimapTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: type.Bug, severity.Low

#98 Fix bug with optional dates check
  src/main/java/seedu/address/model/prescription/IsValidDatesPredicate.java
Labels: type.Bug, priority.High

#102 Fix bug causing ListView to disappear
  src/main/java/seedu/address/ui/PrescriptionCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/dummy.fxml
Labels: type.Bug, priority.High, severity.Medium

#94 Add tests
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: type.Task, priority.Medium

#108 Add listCompleted command
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ListCompletedCommand.java
  src/main/java/seedu/address/logic/parser/ListCompletedCommandParser.java
  src/main/java/seedu/address/logic/parser/PrescriptionListParser.java
  src/main/java/seedu/address/model/prescription/Prescription.java
  src/main/java/seedu/address/storage/CompletedPrescriptionListStorage.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: type.Task, priority.High

#114 Update add command implementation for DG
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High

#113 Add tests
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/TakeCommandTest.java
  src/test/java/seedu/address/logic/commands/UntakeCommandTest.java
  src/test/java/seedu/address/logic/parser/PrescriptionListParserTest.java
  src/test/java/seedu/address/model/prescription/PrescriptionTest.java
Labels: type.Task, priority.Medium

#122 Clean up and make minor changes to commands
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListCompletedCommand.java
  src/main/java/seedu/address/logic/commands/TakeCommand.java
  src/main/java/seedu/address/logic/commands/UntakeCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/TakeCommandParser.java
  src/main/java/seedu/address/logic/parser/UntakeCommandParser.java
  src/main/java/seedu/address/model/prescription/IsCompletedPredicate.java
  src/main/java/seedu/address/model/prescription/IsTodayPredicate.java
  src/main/java/seedu/address/model/prescription/IsValidDatesPredicate.java
  src/main/java/seedu/address/model/prescription/Stock.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCompletedCommandTest.java
  src/test/java/seedu/address/logic/commands/TakeCommandTest.java
  src/test/java/seedu/address/logic/commands/UntakeCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/PrescriptionListParserTest.java
  src/test/java/seedu/address/logic/parser/TakeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UntakeCommandParserTest.java
Labels: type.Task, priority.Medium

#123 Add DG details for Add and ListToday
  docs/DeveloperGuide.md
  docs/diagrams/AddCommandActivityDiagram.puml
  docs/diagrams/AddCommandSequenceDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ListTodayCommandActivityDiagram.puml
  docs/diagrams/ListTodayCommandSequenceDiagram.puml
Labels: type.Documentation, priority.High

#124 Branch update dg edit
  docs/DeveloperGuide.md
  docs/diagrams/EditCommandClassDiagram.puml
Labels: type.Documentation, priority.High

#126 Add test coverage for CommandResult
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ListCompletedCommandTest.java
  src/test/java/seedu/address/model/prescription/IsValidDatesPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalPrescriptions.java
Labels: priority.Low

#128 Update take feature in DG and fix typos
  docs/DeveloperGuide.md
  docs/diagrams/TakeCommandClassDiagram.puml
  src/main/java/seedu/address/logic/parser/TakeCommandParser.java
Labels: type.Documentation, priority.High

#129 Update moving of prescriptions to completed list
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: help wanted, type.Task, priority.Medium

#134 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/CheckInteractionOOD.puml
  docs/diagrams/StorageClassDiagram.puml
Labels: type.Documentation, priority.Medium

#131 Update version number and build gradle for trial jar
  build.gradle
  src/main/java/seedu/address/MainApp.java
Labels: type.Task, priority.High

#141 Fix typo
  docs/DeveloperGuide.md
  docs/diagrams/CheckInteractionOOD.puml
Labels: type.Documentation, priority.High

#136 Update add command and general details for UG
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/ui/Ui-add.png
Labels: type.Documentation, priority.High

#143 Update UG
  docs/UserGuide.md
  docs/images/ui/Ui-delete.png
  docs/images/ui/Ui-list.png
Labels: type.Documentation, priority.High

#145 Update take UG
  docs/UserGuide.md
  docs/images/ui/Ui-take.png
Labels: type.Documentation, priority.High

#144 update ug for edit, listtoday and reminder command
  docs/UserGuide.md
  docs/images/ui/Ui-Edit.png
  docs/images/ui/Ui-ListToday.png
  docs/images/ui/Ui-Reminder.png
Labels: type.Documentation, priority.High, severity.VeryLow

#150 Add content to UG
  docs/UserGuide.md
  docs/images/ui/Ui-find.png
Labels: type.Documentation, priority.High

#142 Add logic to label behaviour
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/model/prescription/Prescription.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PrescriptionCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PrescriptionListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/model/prescription/PrescriptionTest.java
Labels: type.Enhancement, priority.Medium
