Repository AY2324S1-CS2103T-T15-2/tp, pull requests merged in 2023-11, with the labels that each got.

#153 Change aesthetics for UG according to 2101 consult
  README.md
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#157 Implement substring match
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: type.Enhancement, priority.High

#158 Fix minor style and logic bugs
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListCompletedCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/TakeCommandParser.java
  src/main/java/seedu/address/logic/parser/UntakeCommandParser.java
  src/main/java/seedu/address/model/prescription/IsAboutToExpirePredicate.java
  src/main/java/seedu/address/model/prescription/IsLowInStockPredicate.java
  src/main/java/seedu/address/model/prescription/IsValidDatesPredicate.java
  src/main/java/seedu/address/model/prescription/Prescription.java
  src/main/java/seedu/address/model/prescription/Stock.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Task, type.Bug, priority.High

#160 Update implementation of predicates
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListTodayCommand.java
  src/main/java/seedu/address/logic/commands/ReminderCommand.java
  src/main/java/seedu/address/logic/commands/TakeCommand.java
  src/main/java/seedu/address/logic/commands/UntakeCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/prescription/Prescription.java
  src/main/java/seedu/address/model/prescription/SameNamePredicate.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PrescriptionCard.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/prescription/PrescriptionTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPrescriptionTest.java
Labels: type.Task, priority.High

#165 Update UG
  docs/UserGuide.md
  src/main/java/seedu/address/model/Model.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/TakeCommandTest.java
Labels: type.Documentation, priority.High

#164 Update UG
  docs/UserGuide.md
  docs/images/ui/Ui-listAllConflicts.png
  docs/images/ui/Ui-listConflicts.png
Labels: type.Documentation, priority.High

#168 Update take and untake in UG
  docs/UserGuide.md
  docs/images/ui/Ui-take.png
  docs/images/ui/Ui-take1.png
  docs/images/ui/Ui-take2.png
  docs/images/ui/Ui-untake1.png
  docs/images/ui/Ui-untake2.png
Labels: type.Documentation, priority.High

#167 Edit add command documentation
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#206 Fix bug in edit command
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Task, priority.High

#204 Update untake feature in UG
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#208 Improve tests
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/ListAllConflictsCommandTest.java
  src/test/java/seedu/address/testutil/PrescriptionBuilder.java
Labels: type.Task, priority.High

#210 Fix UI bugs for long strings in PrescriptionCard
  src/main/resources/view/PrescriptionListCard.fxml
Labels: type.Bug, severity.Low

#211 fix date not exist bugs
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/prescription/Date.java
  src/main/java/seedu/address/storage/JsonAdaptedPrescription.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/prescription/DateTest.java
Labels: type.Bug, priority.High, severity.High

#209 Improve tests
  src/main/java/seedu/address/logic/commands/ListConflictsCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/commands/ListConflictsCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ListAllConflictsCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ListConflictsCommandParserTest.java
Labels: type.Task, priority.High

#212 prevent users from inputting values exceeding MAX_INT
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/prescription/Dosage.java
  src/main/java/seedu/address/model/prescription/Stock.java
  src/main/java/seedu/address/storage/JsonAdaptedPrescription.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/prescription/StockTest.java
Labels: type.Bug, priority.High, severity.High

#213 fix dates bug
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/prescription/IsValidDatesPredicate.java
  src/test/java/seedu/address/model/prescription/IsValidDatesPredicateTest.java
Labels: type.Bug, priority.High, severity.High

#214 Update DG with UI design considerations
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.Medium

#216 update ug bugs
  docs/UserGuide.md
Labels: type.Documentation, type.Bug, priority.High

#217 Update PPP
  docs/team/teerenjing.md
Labels: type.Documentation, type.Task, priority.High

#218 Update RoeReRe.md
  docs/team/roerere.md
Labels: type.Documentation, priority.High

#220 Update PPP
  docs/team/chongweijie29.md
Labels: type.Documentation, priority.High

#219 Standardise some aspects of UG for v1.4
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/prescription/Dosage.java
  src/main/java/seedu/address/model/prescription/Stock.java
Labels: type.Documentation, priority.High

#226 Update PPP
  docs/team/jingyu987.md
Labels: type.Documentation, priority.High

#227 Update PPP
  docs/team/shyanyong.md
Labels: type.Documentation, priority.High

#228 Fix UG bugs, add ToC and GUI details, change style
  docs/UserGuide.md
Labels: type.Documentation, priority.Medium

#229 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
Labels: type.Documentation, priority.High

#230 Update UG
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#231 Change UG style
  docs/UserGuide.md
  docs/stylesheets/main.css
Labels: type.Documentation, priority.Medium

#232 Update UG
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#233 Resize all diagrams to match text as closely as possible
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/diagrams/AddCommandSequenceDiagram.puml
  docs/diagrams/CheckInteractionOOD.puml
  docs/diagrams/ListTodayCommandSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/TakeCommandClassDiagram.puml
Labels: type.Documentation, priority.Low, severity.Low

#236 Update JavaDocs
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListConflictsCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/parser/ExitCommandParser.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/logic/parser/ListAllConflictsCommandParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/ListConflictsCommandParser.java
  src/main/java/seedu/address/logic/parser/TakeCommandParser.java
  src/main/java/seedu/address/logic/parser/UntakeCommandParser.java
  src/main/java/seedu/address/model/ReadOnlyPrescriptionList.java
  src/main/java/seedu/address/model/prescription/Dosage.java
  src/main/java/seedu/address/model/prescription/Frequency.java
  src/main/java/seedu/address/model/prescription/Note.java
  src/main/java/seedu/address/model/prescription/Prescription.java
  src/main/java/seedu/address/model/prescription/Stock.java
Labels: type.Task, priority.High

#234 improve code quality
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/PrescriptionListParser.java
  src/main/java/seedu/address/model/prescription/Dosage.java
  src/main/java/seedu/address/model/prescription/IsLowInStockPredicate.java
  src/main/java/seedu/address/model/prescription/IsTodayPredicate.java
  src/main/java/seedu/address/model/prescription/Prescription.java
Labels: priority.Low, severity.VeryLow

#235 edit editcommanddiagram
  docs/DeveloperGuide.md
  docs/diagrams/EditCommandClassDiagram.puml
Labels: type.Documentation, priority.Low, severity.Low

#238 Update PPP
  docs/team/jingyu987.md
Labels: type.Documentation, priority.Low

#242 Add glossary
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#241 Clean test code
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/ui/PrescriptionCard.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/notJsonFormatAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/model/prescription/PrescriptionTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPrescriptionTest.java
  src/test/java/seedu/address/testutil/PrescriptionUtil.java
Labels: type.Documentation, priority.High

#243 Final code edits
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ListConflictsCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/PrescriptionListParserTest.java
Labels: type.Documentation, priority.High

#245 Fix typo in PPP
  docs/team/jingyu987.md
Labels: type.Documentation, priority.Low

#250 Add links to PPP
  docs/team/jingyu987.md
Labels: type.Documentation, priority.High
